const places = [
  "Bamburgh Northumberland UK",
  "Llandudno Conwy (W) UK",
  "St Andrews Fife (S) UK",
  "Dartmouth Devon UK",
  "Tenby Pembrokeshire (W) UK",
  "St Davids Pembrokeshire (W) UK",
  "Aldeburgh Suffolk UK",
  "Filey North Yorkshire UK",
  "Conwy Conwy (W) UK",
  "Lyme Regis Dorset UK",
  "Lynmouth Devon UK",
  "Lytham St Annes Lancashire UK",
  "Robin Hood's Bay North Yorkshire UK",
  "Southwold Suffolk UK",
  "St Mawes Cornwall UK",
  "Lymington Hampshire UK",
  "Wells-next-the-sea Norfolk UK",
  "Whitby North Yorkshire UK",
  "Beaumaris Anglesey (W) UK",
  "North Berwick East Lothian (S) UK",
  "Sidmouth Devon UK",
  "Rye East Sussex UK",
  "Berwick-upon-Tweed Northumberland UK",
  "Blakeney Norfolk UK",
  "Bude Cornwall UK",
  "Saltburn-by-the-Sea North Yorkshire UK",
  "Deal Kent UK",
  "Fowey Cornwall UK",
  "Looe Cornwall UK",
  "Saundersfoot Pembrokeshire (W) UK",
  "Sheringham Norfolk UK",
  "Southsea Hampshire UK",
  "Swanage Dorset UK",
  "Broadstairs Kent UK",
  "Exmouth Devon UK",
  "Tynemouth Tyne and Wear UK",
  "Eastbourne East Sussex UK",
  "Folkestone Kent UK",
  "Mevagissey Cornwall UK",
  "Weymouth Dorset UK",
  "Ayr Ayrshire (S) UK",
  "Salcombe Devon UK",
  "Scarborough North Yorkshire UK",
  "Seahouses Northumberland UK",
  "Ventnor Isle of Wight UK",
  "Brixham Devon UK",
  "Falmouth Cornwall UK",
  "New Brighton Merseyside UK",
  "St Ives Cornwall UK",
  "Teignmouth Devon UK",
  "Whitley Bay Tyne and Wear UK",
  "Plymouth Devon UK",
  "Bournemouth Dorset UK",
  "Grange-over-Sands Cumbria UK",
  "Swansea Swansea (W) UK",
  "Whitstable Kent UK",
  "Brighton East Sussex UK",
  "Hastings East Sussex UK",
  "Huntstanton Norfolk UK",
  "Poole Dorset UK",
  "Dungeness Kent UK",
  "Ramsgate Kent UK",
  "Aberystwyth Ceredigion (W) UK",
  "Cromer Norfolk UK",
  "Morecambe Lancashire UK",
  "Oban Argyll and Bute (S) UK",
  "Padstow Cornwall UK",
  "Shanklin Isle of Wight UK",
  "Worthing West Sussex UK",
  "Dawlish Devon UK",
  "Penzance Cornwall UK",
  "Bridlington East Yorkshire UK",
  "Ilfracombe Devon UK",
  "Southport Merseyside UK",
  "Minehead Somerset UK",
  "Littlehampton West Sussex UK",
  "Torquay Devon UK",
  "Blackpool Lancashire UK”",
  "Weston-super-Mare Somerset UK",
  "Margate Kent UK",
  "Newquay Cornwall UK",
  "Herne Bay Kent UK",
  "Burnham-on-Sea Somerset UK",
  "Great Yarmouth Norfolk UK",
  "Southand-on-Sea Essex UK",
  "Bognor Regis West Sussex UK",
  "Skegness Lincolnshire UK",
];

module.exports = places;
